package routes

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"animalpoke/backend/internal/config"
	"animalpoke/backend/internal/models"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// inventoryFile is generated by scripts/api-test-matrix-gate.mjs --write
type inventoryFile struct {
	Count      int `json:"count"`
	Operations []struct {
		Method      string `json:"method"`
		Path        string `json:"path"`
		OperationID string `json:"operationId"`
	} `json:"operations"`
}

// contractOp is one OpenAPI operation under the AP-091 matrix.
type contractOp struct {
	operationID     string
	method          string
	path            string
	successStatuses []int
	failureStatuses []int
	needsDB         bool
	needsAuth       bool
	needsAdmin      bool
	needsOps        bool
	successBody     string
	failureBody     string
	failureNoAuth   bool
	successPath     string
	multipart       bool
}

var contractReqSeq atomic.Uint64

func contractConfig() *config.Config {
	cfg := testConfig()
	cfg.FeatureFlags = config.FeatureFlags{Ranking: true, PvP: true, Social: true, Ops: true}
	cfg.CommerceEnabled = true
	cfg.AdminAPIKey = "admin-test-key-ap091"
	cfg.OpsToken = "ops-test-token-ap091"
	cfg.JWTAccessTTL = 2 * time.Hour
	cfg.AIMockEnabled = true
	return cfg
}

func openContractDB(t *testing.T) *gorm.DB {
	t.Helper()
	dsn := fmt.Sprintf("file:contract_%s?mode=memory&cache=shared", strings.ReplaceAll(uuid.NewString(), "-", ""))
	db, err := gorm.Open(sqlite.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	require.NoError(t, err)
	require.NoError(t, db.AutoMigrate(
		&models.Device{}, &models.Animal{}, &models.AuditLog{}, &models.Inference{},
		&models.DataRequest{}, &models.SecurityReport{}, &models.Product{}, &models.Order{},
		&models.Entitlement{}, &models.ModerationReport{}, &models.Account{},
	))
	return db
}

func mintDeviceJWT(t *testing.T, cfg *config.Config, deviceID string) string {
	t.Helper()
	claims := jwt.MapClaims{
		"device_id": deviceID, "sub": deviceID,
		"iss": cfg.JWTIssuer, "aud": cfg.JWTAudience,
		"jti": uuid.NewString(), "token_version": float64(1),
		"exp": time.Now().Add(time.Hour).Unix(), "iat": time.Now().Unix(),
	}
	tok := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	s, err := tok.SignedString([]byte(cfg.JWTSecret))
	require.NoError(t, err)
	return s
}

var contractPNG = []byte{
	0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
	0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
	0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, 0xde, 0x00, 0x00, 0x00,
	0x0c, 0x49, 0x44, 0x41, 0x54, 0x08, 0xd7, 0x63, 0xf8, 0xff, 0xff, 0x3f,
	0x00, 0x05, 0xfe, 0x02, 0xfe, 0xdc, 0xcc, 0x59, 0xe7, 0x00, 0x00, 0x00,
	0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
}

func findInventoryPath(t *testing.T) string {
	t.Helper()
	candidates := []string{
		filepath.Join("..", "..", "docs", "api-operations.inventory.json"),
		filepath.Join("docs", "api-operations.inventory.json"),
	}
	wd, _ := os.Getwd()
	dir := wd
	for range 6 {
		candidates = append(candidates, filepath.Join(dir, "docs", "api-operations.inventory.json"))
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	for _, p := range candidates {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p
		}
	}
	t.Fatalf("docs/api-operations.inventory.json not found from %s", wd)
	return ""
}

func loadInventoryOps(t *testing.T) []contractOp {
	t.Helper()
	raw, err := os.ReadFile(findInventoryPath(t))
	require.NoError(t, err)
	var inv inventoryFile
	require.NoError(t, json.Unmarshal(raw, &inv))
	require.Greater(t, inv.Count, 0)
	require.Equal(t, inv.Count, len(inv.Operations))

	// Broad status sets: success path is "authenticated request reaches handler".
	// 429 is accepted only as a residual safety net for shared limiters.
	publicSuccess := []int{200, 503}
	publicFail := []int{404, 405}
	authSuccess := []int{200, 201, 202, 204, 400, 401, 403, 404, 409, 422, 429, 500, 501, 503}
	authFail := []int{401, 403, 429}
	adminSuccess := []int{200, 201, 202, 400, 403, 404, 409, 422, 429, 500, 501, 503}
	adminFail := []int{400, 401, 403, 429}
	opsSuccess := []int{200, 201, 202, 400, 403, 404, 409, 422, 429, 500, 501, 503}
	opsFail := []int{400, 401, 403, 429}

	out := make([]contractOp, 0, len(inv.Operations))
	for _, item := range inv.Operations {
		op := contractOp{
			operationID: item.OperationID,
			method:      strings.ToUpper(item.Method),
			path:        item.Path,
		}
		p := item.Path
		id := item.OperationID

		switch {
		case p == "/health" || p == "/livez" || p == "/ready" || p == "/readyz" || p == "/metrics" ||
			p == "/api/v1/ping" || p == "/api/v1/time" || p == "/api/v1/version":
			op.successStatuses = publicSuccess
			if id == "getMetrics" {
				op.successStatuses = []int{200, 404}
			}
			if id == "getReady" || id == "getReadyz" {
				op.successStatuses = []int{200, 503}
			}
			op.failureStatuses = publicFail
		case strings.HasPrefix(p, "/api/v1/admin/"):
			op.needsAdmin = true
			op.needsDB = true
			op.successStatuses = adminSuccess
			op.failureStatuses = adminFail
			op.successBody = defaultBodyFor(id, p, op.method)
		case strings.Contains(p, "/ops/"):
			op.needsOps = true
			op.needsAuth = true
			op.needsDB = true
			op.successStatuses = opsSuccess
			op.failureStatuses = opsFail
			op.failureNoAuth = true
			op.successBody = defaultBodyFor(id, p, op.method)
		case id == "authDevice" || id == "authLogin" || id == "authRefresh" ||
			id == "authEmailVerifyRequest" || id == "authEmailVerify" ||
			id == "authPasswordForgot" || id == "authPasswordReset":
			op.needsDB = true
			op.successStatuses = []int{200, 400, 401, 422, 429, 503}
			op.failureStatuses = []int{400, 401, 422, 429}
			op.successBody = defaultBodyFor(id, p, op.method)
			op.failureBody = `{}`
		default:
			op.needsAuth = true
			op.needsDB = true
			op.successStatuses = authSuccess
			op.failureStatuses = authFail
			op.failureNoAuth = true
			op.successBody = defaultBodyFor(id, p, op.method)
			if id == "visionDetect" || id == "photoScore" || id == "photoCalibrate" {
				op.multipart = true
			}
		}

		op.successPath = fillPathParams(p)
		out = append(out, op)
	}
	return out
}

func fillPathParams(p string) string {
	repl := map[string]string{
		"{id}":          "1",
		"{uuid}":        "00000000-0000-4000-8000-000000000099",
		"{animal_uuid}": "00000000-0000-4000-8000-000000000099",
		"{node_id}":     "node-1",
		"{quest_id}":    "quest-1",
		"{token}":       "share-token-1",
	}
	out := p
	for k, v := range repl {
		out = strings.ReplaceAll(out, k, v)
	}
	for strings.Contains(out, "{") {
		start := strings.Index(out, "{")
		end := strings.Index(out[start:], "}")
		if end < 0 {
			break
		}
		out = out[:start] + "x" + out[start+end+1:]
	}
	return out
}

func defaultBodyFor(id, path, method string) string {
	if method != http.MethodPost && method != http.MethodPut && method != http.MethodPatch {
		return ""
	}
	switch {
	case id == "authDevice":
		return ""
	case id == "authBind" || id == "authLogin":
		return `{"provider":"mock","id_token":"x"}`
	case id == "authRefresh":
		return `{"refresh_token":"invalid-refresh-token"}`
	case strings.Contains(path, "privacy/consent"):
		return `{"version":"1","scopes":{"analytics":true}}`
	case strings.Contains(path, "security/report"):
		return `{"nonce":"n1","risk_level":"low"}`
	case strings.Contains(path, "safety/report"):
		return `{"category":"abuse","detail":"spam"}`
	case strings.Contains(path, "commerce/orders/fulfill"):
		return `{"order_id":"1","platform":"apple","receipt":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}`
	case strings.Contains(path, "commerce/orders/refund") || strings.Contains(path, "admin/commerce/orders/refund"):
		return `{"order_id":"1"}`
	case strings.Contains(path, "commerce/orders") && method == http.MethodPost:
		return `{"product_id":"coins_100","platform":"apple"}`
	case strings.Contains(path, "webhooks/refund"):
		return `{"platform":"apple","receipt":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}`
	case strings.Contains(path, "analytics/events"):
		return `{"schema_version":1,"events":[{"name":"app_open","ts":"2020-01-01T00:00:00Z"}]}`
	case strings.Contains(path, "errors/report"):
		return `{"message":"boom","stack":"at x","release":"test"}`
	case strings.Contains(path, "value/generate"):
		return `{"species":"cat","cuteness":5,"rarity_hint":3}`
	case strings.Contains(path, "vision/analyze"):
		return `{"detect_id":"00000000-0000-0000-0000-000000000001"}`
	case strings.Contains(path, "sync/animals") && method == http.MethodPost && !strings.Contains(path, "{"):
		return `{"items":[]}`
	case strings.Contains(path, "sync/animal"):
		return `{"uuid":"00000000-0000-4000-8000-000000000099","species":"cat","breed":"x","rarity":1,"hp":1,"atk":1,"def":1,"spd":1,"class":"Ranger","element":"Wind","latitude":0,"longitude":0,"generated_at":"2020-01-01T00:00:00Z"}`
	case strings.Contains(path, "game-config/rollback"):
		return `{"version":"game-config.v1"}`
	case strings.Contains(path, "game-config"):
		return `{"version":"game-config.v1","payload":{}}`
	case strings.Contains(path, "pvp/result"):
		return `{"match_id":"m1"}`
	case strings.Contains(path, "social/share"):
		return `{"animal_id":"a1"}`
	case strings.Contains(path, "auth/devices/revoke"):
		return `{"device_id":"other"}`
	case strings.Contains(path, "auth/password"):
		return `{"email":"user@example.com","password":"Password1!","token":"tok"}`
	case strings.Contains(path, "auth/email"):
		return `{"email":"user@example.com","code":"123456"}`
	default:
		return `{}`
	}
}

func containsInt(xs []int, v int) bool {
	for _, x := range xs {
		if x == v {
			return true
		}
	}
	return false
}

func TestContractMatrix(t *testing.T) {
	gin.SetMode(gin.TestMode)
	ops := loadInventoryOps(t)
	require.GreaterOrEqual(t, len(ops), 49, "matrix must cover current OpenAPI operationIds")

	cfg := contractConfig()
	nilRouter := NewRouter(cfg, nil)
	db := openContractDB(t)
	dbRouter := NewRouter(cfg, db)

	seen := map[string]bool{}
	for _, op := range ops {
		op := op
		require.False(t, seen[op.operationID], "duplicate %s", op.operationID)
		seen[op.operationID] = true

		t.Run(op.operationID, func(t *testing.T) {
			r := nilRouter
			if op.needsDB {
				r = dbRouter
			}
			// Fresh device identity per operation avoids device-scoped rate limit bleed.
			opDevice := fmt.Sprintf("contract-%s", uuid.NewString())
			require.NoError(t, db.Create(&models.Device{
				DeviceID: opDevice, InstallationSecretHash: strings.Repeat("b", 64), TokenVersion: 1,
			}).Error)
			token := mintDeviceJWT(t, cfg, opDevice)

			t.Run("success", func(t *testing.T) {
				w := doContractRequest(t, r, cfg, token, op, true)
				assert.Contains(t, op.successStatuses, w.Code, "success status=%d body=%s", w.Code, w.Body.String())
			})
			t.Run("failure", func(t *testing.T) {
				w := doContractRequest(t, r, cfg, token, op, false)
				assert.Contains(t, op.failureStatuses, w.Code, "failure status=%d body=%s", w.Code, w.Body.String())
				assert.NotContains(t, []int{http.StatusOK, http.StatusCreated, http.StatusAccepted}, w.Code)
			})
		})
	}
	require.Equal(t, len(ops), len(seen))
}

func doContractRequest(t *testing.T, r *gin.Engine, cfg *config.Config, token string, op contractOp, success bool) *httptest.ResponseRecorder {
	t.Helper()
	method := op.method
	path := op.path
	if success && op.successPath != "" {
		path = op.successPath
	}
	if !success && !op.failureNoAuth && !op.needsAuth && !op.needsAdmin && !op.needsOps && op.failureBody == "" && method == http.MethodGet {
		method = http.MethodPut
	}
	path = fillPathParams(path)

	var body io.Reader
	contentType := ""
	if success && op.multipart {
		var buf bytes.Buffer
		b := "contractboundary"
		contentType = "multipart/form-data; boundary=" + b
		buf.WriteString("--" + b + "\r\n")
		buf.WriteString(`Content-Disposition: form-data; name="image"; filename="t.png"` + "\r\n")
		buf.WriteString("Content-Type: image/png\r\n\r\n")
		buf.Write(contractPNG)
		buf.WriteString("\r\n--" + b + "--\r\n")
		body = &buf
	} else {
		payload := op.successBody
		if success && op.operationID == "authDevice" {
			payload = fmt.Sprintf(`{"device_id":"%s"}`, "dev-"+uuid.NewString())
		}
		if !success {
			payload = op.failureBody
			if payload == "" && (method == http.MethodPost || method == http.MethodPut || method == http.MethodPatch) {
				payload = `{}`
			}
		}
		if payload != "" {
			body = strings.NewReader(payload)
			contentType = "application/json"
		}
	}

	req := httptest.NewRequest(method, path, body)
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	// Unique client IP per request to avoid admin/IP token-bucket bleed across 100+ ops.
	n := contractReqSeq.Add(1)
	req.Header.Set("X-Forwarded-For", fmt.Sprintf("203.0.113.%d", (n%250)+1))
	req.RemoteAddr = fmt.Sprintf("198.51.100.%d:45678", (n%250)+1)

	if success {
		if op.needsAuth {
			req.Header.Set("Authorization", "Bearer "+token)
		}
		if op.needsAdmin {
			req.Header.Set("X-Admin-Key", cfg.AdminAPIKey)
			req.Header.Set("X-Admin-Reason", "ap091-contract-matrix")
		}
		if op.needsOps {
			req.Header.Set("X-AP-Ops-Token", cfg.OpsToken)
		}
	} else {
		if op.needsAdmin {
			req.Header.Set("X-Admin-Key", "wrong-admin-key")
		}
		if op.needsOps {
			req.Header.Set("X-AP-Ops-Token", "wrong-ops-token")
		}
	}

	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	return w
}

// silence unused helper in some toolchains
var _ = containsInt
