import type { AchievementDef, AchievementCategory } from './types'

/** 成就类别显示配置 */
export const CATEGORY_LABELS: Record<AchievementCategory, string> = {
  collection: '收集',
  battle: '战斗',
  exploration: '探索',
  social: '社交',
  milestone: '里程碑',
}

/** 成就稀有度显示配置 */
export const RARITY_LABELS: Record<string, string> = {
  bronze: '铜',
  silver: '银',
  gold: '金',
  platinum: '铂',
}

/** 成就稀有度颜色（CSS 变量） */
export const ACHIEVEMENT_RARITY_COLORS: Record<string, string> = {
  bronze: 'var(--rarity-common)',
  silver: 'var(--rarity-uncommon)',
  gold: 'var(--rarity-epic)',
  platinum: 'var(--rarity-legendary)',
}

/** 成就定义表（22 项） */
export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  // ===== 收集类（7 项） =====
  {
    id: 'first_capture',
    name: '初出茅庐',
    description: '收藏第 1 只动物',
    category: 'collection',
    rarity: 'bronze',
    icon: '🎯',
    target: 1,
    reward: { gold: 50 },
    condition: { type: 'total_captures', target: 1 },
  },
  {
    id: 'collector_50',
    name: '收藏家',
    description: '收藏 50 只动物',
    category: 'collection',
    rarity: 'silver',
    icon: '📦',
    target: 50,
    reward: { gold: 200, title: '收藏家' },
    condition: { type: 'total_captures', target: 50 },
  },
  {
    id: 'dex_master_200',
    name: '图鉴大师',
    description: '收藏 200 只动物',
    category: 'collection',
    rarity: 'gold',
    icon: '📖',
    target: 200,
    reward: { gold: 500, title: '图鉴大师' },
    condition: { type: 'total_captures', target: 200 },
  },
  {
    id: 'rare_collector_10',
    name: '稀有猎人',
    description: '捕获 10 只稀有(Rare)动物',
    category: 'collection',
    rarity: 'silver',
    icon: '💎',
    target: 10,
    reward: { gold: 150 },
    condition: { type: 'captures_by_rarity', rarity: 'rare', target: 10 },
  },
  {
    id: 'epic_collector_5',
    name: '史诗收藏',
    description: '捕获 5 只史诗(Epic)动物',
    category: 'collection',
    rarity: 'gold',
    icon: '🔮',
    target: 5,
    reward: { gold: 300, title: '史诗收藏家' },
    condition: { type: 'captures_by_rarity', rarity: 'epic', target: 5 },
  },
  {
    id: 'legendary_captured',
    name: '传说降临',
    description: '捕获第 1 只传说级动物',
    category: 'collection',
    rarity: 'platinum',
    icon: '⭐',
    target: 1,
    reward: { gold: 500, title: '传说捕手' },
    condition: { type: 'legendary_captured' },
  },
  {
    id: 'cat_lover_10',
    name: '爱猫人士',
    description: '捕获 10 只猫',
    category: 'collection',
    rarity: 'bronze',
    icon: '🐱',
    target: 10,
    reward: { gold: 100 },
    condition: { type: 'captures_by_species', species: 'cat', target: 10 },
  },

  // ===== 战斗类（5 项） =====
  {
    id: 'first_battle_win',
    name: '初战告捷',
    description: '赢得第 1 场战斗',
    category: 'battle',
    rarity: 'bronze',
    icon: '⚔️',
    target: 1,
    reward: { gold: 50 },
    condition: { type: 'total_battles_won', target: 1 },
  },
  {
    id: 'battler_50',
    name: '斗士',
    description: '参与 50 场战斗',
    category: 'battle',
    rarity: 'silver',
    icon: '🛡️',
    target: 50,
    reward: { gold: 200 },
    condition: { type: 'total_battles', target: 50 },
  },
  {
    id: 'win_streak_5',
    name: '连胜达人',
    description: '获得 5 连胜',
    category: 'battle',
    rarity: 'silver',
    icon: '🔥',
    target: 5,
    reward: { gold: 200, title: '连胜达人' },
    condition: { type: 'win_streak', target: 5 },
  },
  {
    id: 'battler_100',
    name: '百战不殆',
    description: '参与 100 场战斗',
    category: 'battle',
    rarity: 'gold',
    icon: '🗡️',
    target: 100,
    reward: { gold: 400, title: '百战勇士' },
    condition: { type: 'total_battles', target: 100 },
  },
  {
    id: 'battle_master_50_wins',
    name: '常胜将军',
    description: '赢得 50 场战斗',
    category: 'battle',
    rarity: 'gold',
    icon: '👑',
    target: 50,
    reward: { gold: 500, title: '常胜将军' },
    condition: { type: 'total_battles_won', target: 50 },
  },

  // ===== 探索类（4 项） =====
  {
    id: 'explorer_5_cities',
    name: '区域探索者',
    description: '在 5 个不同城市捕获过动物',
    category: 'exploration',
    rarity: 'silver',
    icon: '🗺️',
    target: 5,
    reward: { gold: 200 },
    condition: { type: 'cities_visited', target: 5 },
  },
  {
    id: 'rain_warrior',
    name: '雨天勇士',
    description: '雨天捕获 10 只且无感冒',
    category: 'exploration',
    rarity: 'silver',
    icon: '🌧️',
    target: 10,
    reward: { gold: 150, title: '雨天勇士' },
    condition: { type: 'rain_captures_no_cold', target: 10 },
  },
  {
    id: 'weather_master',
    name: '天气大师',
    description: '经历所有 7 种天气类型',
    category: 'exploration',
    rarity: 'gold',
    icon: '🌤️',
    target: 7,
    reward: { gold: 300, title: '天气大师' },
    condition: { type: 'all_weather_types' },
  },
  {
    id: 'explorer_10_cities',
    name: '环球旅行家',
    description: '在 10 个不同城市捕获过动物',
    category: 'exploration',
    rarity: 'gold',
    icon: '🧭',
    target: 10,
    reward: { gold: 500, title: '环球旅行家' },
    condition: { type: 'cities_visited', target: 10 },
  },

  // ===== 社交类（2 项，预留） =====
  {
    id: 'guild_member',
    name: '社交新星',
    description: '加入一个公会',
    category: 'social',
    rarity: 'bronze',
    icon: '🤝',
    target: 1,
    reward: { gold: 100 },
    condition: { type: 'cities_visited', target: 0 },
  },
  {
    id: 'guild_leader',
    name: '社团领袖',
    description: '创建一个公会',
    category: 'social',
    rarity: 'silver',
    icon: '🏅',
    target: 1,
    reward: { gold: 200, title: '社团领袖' },
    condition: { type: 'cities_visited', target: 999 },
  },

  // ===== 里程碑类（4 项） =====
  {
    id: 'level_5',
    name: '小有所成',
    description: '达到等级 5',
    category: 'milestone',
    rarity: 'silver',
    icon: '⬆️',
    target: 5,
    reward: { gold: 200 },
    condition: { type: 'level_reached', target: 5 },
  },
  {
    id: 'level_10',
    name: '满级达成',
    description: '达到等级 10（满级）',
    category: 'milestone',
    rarity: 'platinum',
    icon: '🏆',
    target: 10,
    reward: { gold: 1000, title: '巅峰大师' },
    condition: { type: 'level_reached', target: 10 },
  },
  {
    id: 'check_in_7_days',
    name: '坚持就是胜利',
    description: '连续签到 7 天',
    category: 'milestone',
    rarity: 'bronze',
    icon: '📅',
    target: 7,
    reward: { gold: 100 },
    condition: { type: 'check_in_days', target: 7 },
  },
  {
    id: 'check_in_30_days',
    name: '月度坚持',
    description: '累计签到 30 天',
    category: 'milestone',
    rarity: 'gold',
    icon: '📆',
    target: 30,
    reward: { gold: 500, title: '坚持之星' },
    condition: { type: 'check_in_days', target: 30 },
  },
]

/** 成就 ID → 定义映射（便于快速查找） */
export const ACHIEVEMENT_MAP: Record<string, AchievementDef> = Object.fromEntries(
  ACHIEVEMENT_DEFS.map((def) => [def.id, def])
)

/** AchievementContext localStorage 存储 key */
export const ACHIEVEMENT_STORAGE_KEY = 'animal_poke_achievement'
